# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
r_github_packages: jimhester/covr
matrix:
  include:
  - pandoc: false
    r: release
  - r_github_packages:
    - tidyverse/dplyr
    - jimhester/covr
    r: release
after_success:
  - Rscript run-covr.R

