# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
env:
  - CACHE_VERSION=standard
matrix:
  include:
  - pandoc: false
    r: release
  - r_github_packages:
    - tidyverse/dplyr
    r: release
    env:
      - CACHE_VERSION=github_dplyr
  - install:
    - R -e 'install.packages(c("knitr", "rmarkdown", "devtools", "testthat"))'
    - R -e 'devtools::install_deps(deps = c("Imports", "Depends", "LinkingTo"))'
    r: release
    r_build_args: --no-build-vignettes
    r_check_args: --no-vignettes
    env:
      - CACHE_VERSION=no_suggests
      - _R_CHECK_FORCE_SUGGESTS_=FALSE
after_success:
  - Rscript run-covr.R

