# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
env:
  - CACHE_VERSION=standard
matrix:
  include:
  - pandoc: false
    r: release
  - r_github_packages:
    - tidyverse/dplyr
    r: release
    env:
      - CACHE_VERSION=github_dplyr
after_success:
  - Rscript run-covr.R

