# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
env:
  - CACHE_VERSION=standard
matrix:
  include:
# check it can build without pandoc
  - pandoc: false
    r: release
# check it can build with latest github of important packages
  - r_github_packages:
    - tidyverse/dplyr
    - tidymodels/broom
    - bbolker/broom.mixed
    - tidyverse/tidyselect
    - tidyverse/stringr
    - hadley/assertthat
    - davidgohel/flextable
    - davidgohel/officer
    - yihui/knitr
    - rstudio/rmarkdown
    r: release
    env:
      - CACHE_VERSION=github_packages
# run tests without Suggested packages
  - install:
    - R -e 'install.packages(c("knitr", "rmarkdown", "devtools", "testthat"))'
    - R -e 'devtools::install_deps(deps = c("Imports", "Depends", "LinkingTo"))'
    r: devel
    r_build_args: --no-build-vignettes
    r_check_args: --no-vignettes --no-examples --ignore-vignettes
    env:
      - CACHE_VERSION=no_suggests
      - _R_CHECK_FORCE_SUGGESTS_=FALSE
      - _R_CHECK_RD_XREFS_=FALSE
after_success:
  - Rscript run-covr.R

