# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - osx
  - linux
brew_packages: openssl
r_github_packages: jimhester/covr
matrix:
  include:
  - pandoc: false
    r: release
    os: linux
  - r_github_packages:
    - tidyverse/dplyr
    - jimhester/covr
    r: release
    os: linux
  exclude:
    - r: oldrel
      os: osx
after_success:
  - Rscript run-covr.R

